import '../core/logger.dart';
import 'email_message.dart';
import 'email_service.dart';

/// Sends OTP and verification-link emails with built-in HTML templates.
///
/// Configure once per provider/app-name, then call the appropriate method:
///
/// ```dart
/// final mailer = VerificationMailer(
///   fromEmail: 'noreply@myapp.com',
///   appName: 'MyApp',
///   otpTtl: Duration(minutes: 10),
/// );
///
/// // Send a 6-digit OTP:
/// await mailer.sendOtp(toEmail: 'user@example.com', otp: '847261');
///
/// // Send a magic link:
/// await mailer.sendVerificationLink(
///   toEmail: 'user@example.com',
///   verificationUrl: 'https://myapp.com/verify?token=abc123',
/// );
///
/// // Send a welcome email:
/// await mailer.sendWelcome(toEmail: 'user@example.com', userName: 'Alice');
/// ```
class VerificationMailer {
  /// Creates a verification mailer.
  ///
  /// [fromEmail] must match the sender address configured in your provider.
  /// [appName] is displayed in the subject and body of every email.
  /// [otpTtl] controls the expiry time displayed in OTP emails (default 10 min).
  const VerificationMailer({
    required String fromEmail,
    required String appName,
    Duration otpTtl = const Duration(minutes: 10),
  })  : _fromEmail = fromEmail,
        _appName = appName,
        _otpTtl = otpTtl;

  // ignore: unused_field — stored for subclass/provider use or future from-address support
  final String _fromEmail;
  final String _appName;
  final Duration _otpTtl;

  static const String _tag = 'VerificationMailer';

  // ---------------------------------------------------------------------------
  // OTP
  // ---------------------------------------------------------------------------

  /// Sends a one-time password email to [toEmail].
  ///
  /// [otp] is the code to display — typically 4–8 digits generated by your
  /// auth system. The email displays the TTL from [otpTtl] automatically.
  Future<EmailResult> sendOtp({
    required String toEmail,
    required String otp,
  }) async {
    PrimekitLogger.debug(
      'Sending OTP email to $toEmail',
      tag: _tag,
    );

    final ttlLabel = _formatTtl(_otpTtl);

    final message = EmailMessage(
      to: toEmail,
      subject: '$_appName — Your verification code',
      textBody: _otpTextBody(otp: otp, ttlLabel: ttlLabel),
      htmlBody: _otpHtmlBody(otp: otp, ttlLabel: ttlLabel),
    );

    return EmailService.instance.send(message);
  }

  // ---------------------------------------------------------------------------
  // Verification link
  // ---------------------------------------------------------------------------

  /// Sends a magic-link / email-verification email to [toEmail].
  ///
  /// [verificationUrl] is the full URL the user clicks to verify their address.
  Future<EmailResult> sendVerificationLink({
    required String toEmail,
    required String verificationUrl,
  }) async {
    PrimekitLogger.debug(
      'Sending verification link email to $toEmail',
      tag: _tag,
    );

    final message = EmailMessage(
      to: toEmail,
      subject: 'Verify your $_appName email address',
      textBody: _linkTextBody(verificationUrl: verificationUrl),
      htmlBody: _linkHtmlBody(verificationUrl: verificationUrl),
    );

    return EmailService.instance.send(message);
  }

  // ---------------------------------------------------------------------------
  // Welcome
  // ---------------------------------------------------------------------------

  /// Sends a welcome email to [toEmail] for a newly registered [userName].
  Future<EmailResult> sendWelcome({
    required String toEmail,
    required String userName,
  }) async {
    PrimekitLogger.debug(
      'Sending welcome email to $toEmail',
      tag: _tag,
    );

    final message = EmailMessage(
      to: toEmail,
      toName: userName,
      subject: 'Welcome to $_appName, $userName!',
      textBody: _welcomeTextBody(userName: userName),
      htmlBody: _welcomeHtmlBody(userName: userName),
    );

    return EmailService.instance.send(message);
  }

  // ---------------------------------------------------------------------------
  // Text templates
  // ---------------------------------------------------------------------------

  String _otpTextBody({required String otp, required String ttlLabel}) => '''
Your $_appName verification code

$otp

This code expires in $ttlLabel. Do not share it with anyone.

If you did not request this code, please ignore this email.

— The $_appName team
''';

  String _linkTextBody({required String verificationUrl}) => '''
Verify your email address

Please click the link below to verify your $_appName account:

$verificationUrl

This link expires in ${_formatTtl(_otpTtl)}. If you did not create an account,
please ignore this email.

— The $_appName team
''';

  String _welcomeTextBody({required String userName}) => '''
Welcome to $_appName, $userName!

We're thrilled to have you on board. Your account is all set up and ready to go.

Get started by opening the app and exploring everything $_appName has to offer.

If you have any questions, reply to this email — we're here to help.

— The $_appName team
''';

  // ---------------------------------------------------------------------------
  // HTML templates
  // ---------------------------------------------------------------------------

  String _otpHtmlBody({required String otp, required String ttlLabel}) {
    final escapedOtp = _escapeHtml(otp);
    final escapedApp = _escapeHtml(_appName);

    return '''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Verification Code</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0"
    style="background:#f9fafb;padding:32px 16px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0"
          style="max-width:480px;background:#ffffff;border-radius:16px;
          box-shadow:0 2px 8px rgba(0,0,0,0.08);overflow:hidden;">

          <!-- Header -->
          <tr>
            <td style="padding:32px 24px 24px;text-align:center;">
              <h1 style="margin:0;font-size:24px;font-weight:700;
                color:#111827;">$escapedApp</h1>
              <p style="margin:8px 0 0;font-size:15px;color:#6b7280;">
                Your verification code
              </p>
            </td>
          </tr>

          <!-- OTP box -->
          <tr>
            <td style="padding:0 24px 32px;text-align:center;">
              <div style="display:inline-block;background:#f3f4f6;
                border-radius:12px;padding:20px 40px;margin:0 auto;">
                <span style="font-size:42px;font-weight:800;
                  color:#111827;letter-spacing:12px;font-variant-numeric:tabular-nums;">
                  $escapedOtp
                </span>
              </div>
              <p style="margin:20px 0 0;font-size:14px;color:#6b7280;">
                Expires in <strong style="color:#374151;">$ttlLabel</strong>.
                Never share this code.
              </p>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:0 24px;">
              <hr style="border:none;border-top:1px solid #f3f4f6;margin:0;">
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:20px 24px;text-align:center;">
              <p style="margin:0;font-size:12px;color:#9ca3af;">
                If you didn&rsquo;t request this code, you can safely ignore
                this email.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
''';
  }

  String _linkHtmlBody({required String verificationUrl}) {
    final escapedUrl = _escapeHtml(verificationUrl);
    final escapedApp = _escapeHtml(_appName);
    final ttlLabel = _formatTtl(_otpTtl);

    return '''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Verify your email</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0"
    style="background:#f9fafb;padding:32px 16px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0"
          style="max-width:480px;background:#ffffff;border-radius:16px;
          box-shadow:0 2px 8px rgba(0,0,0,0.08);overflow:hidden;">

          <!-- Header -->
          <tr>
            <td style="padding:32px 24px 8px;text-align:center;">
              <h1 style="margin:0;font-size:24px;font-weight:700;
                color:#111827;">Verify your email</h1>
              <p style="margin:12px 0 0;font-size:15px;color:#6b7280;
                line-height:1.6;">
                Click the button below to verify your email address and
                activate your $escapedApp account.
              </p>
            </td>
          </tr>

          <!-- CTA button -->
          <tr>
            <td style="padding:28px 24px;text-align:center;">
              <a href="$escapedUrl"
                style="display:inline-block;background:linear-gradient(
                  135deg,#667eea,#764ba2);color:#ffffff;text-decoration:none;
                  font-size:16px;font-weight:600;padding:14px 36px;
                  border-radius:8px;letter-spacing:0.01em;">
                Verify Email Address
              </a>
              <p style="margin:16px 0 0;font-size:13px;color:#9ca3af;">
                This link expires in $ttlLabel.
              </p>
            </td>
          </tr>

          <!-- Fallback URL -->
          <tr>
            <td style="padding:0 24px 24px;">
              <p style="margin:0;font-size:12px;color:#9ca3af;text-align:center;">
                If the button doesn&rsquo;t work, copy and paste this URL:<br>
                <a href="$escapedUrl"
                  style="color:#667eea;word-break:break-all;font-size:11px;">
                  $escapedUrl
                </a>
              </p>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:0 24px;">
              <hr style="border:none;border-top:1px solid #f3f4f6;margin:0;">
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:20px 24px;text-align:center;">
              <p style="margin:0;font-size:12px;color:#9ca3af;">
                If you didn&rsquo;t create a $escapedApp account, you can
                safely ignore this email.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
''';
  }

  String _welcomeHtmlBody({required String userName}) {
    final escapedName = _escapeHtml(userName);
    final escapedApp = _escapeHtml(_appName);

    return '''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Welcome to $escapedApp</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;
  font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0"
    style="background:#f9fafb;padding:32px 16px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0"
          style="max-width:480px;background:#ffffff;border-radius:16px;
          box-shadow:0 2px 8px rgba(0,0,0,0.08);overflow:hidden;">

          <!-- Hero banner -->
          <tr>
            <td style="background:linear-gradient(135deg,#667eea,#764ba2);
              padding:40px 24px;text-align:center;">
              <h1 style="margin:0;font-size:28px;font-weight:800;
                color:#ffffff;">Welcome aboard, $escapedName!</h1>
              <p style="margin:10px 0 0;font-size:16px;color:rgba(255,255,255,0.85);">
                You&rsquo;re now part of $escapedApp.
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:32px 24px;">
              <p style="margin:0 0 16px;font-size:15px;color:#374151;
                line-height:1.7;">
                We&rsquo;re thrilled to have you with us. Your account is set
                up and ready — dive in whenever you&rsquo;re ready.
              </p>
              <p style="margin:0;font-size:15px;color:#374151;line-height:1.7;">
                If you ever have questions or run into trouble, just reply to
                this email. We read every message.
              </p>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:0 24px;">
              <hr style="border:none;border-top:1px solid #f3f4f6;margin:0;">
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:20px 24px;text-align:center;">
              <p style="margin:0;font-size:13px;color:#6b7280;">
                — The $escapedApp team
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
''';
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  static String _formatTtl(Duration duration) {
    if (duration.inDays >= 1) {
      final days = duration.inDays;
      return '$days ${days == 1 ? "day" : "days"}';
    }
    if (duration.inHours >= 1) {
      final hours = duration.inHours;
      return '$hours ${hours == 1 ? "hour" : "hours"}';
    }
    final minutes = duration.inMinutes;
    return '$minutes ${minutes == 1 ? "minute" : "minutes"}';
  }

  static String _escapeHtml(String text) => text
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#039;');
}
