# TODO: melos is no longer needed — single package now. Can be deleted after verifying CI.
name: primekit

packages:
  - .

scripts:
  analyze:
    run: flutter analyze --no-fatal-warnings --no-fatal-infos lib/
    description: Analyze the package

  test:
    run: flutter test
    description: Run tests

  format:
    run: dart format .
    description: Format the package
