import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// Callback type for FCM background message handlers.
///
/// Must be a top-level or static function — Flutter runs it in a separate
/// isolate. Keep work minimal as the OS may kill the isolate at any time.
typedef FirebaseMessageHandler = Future<void> Function(RemoteMessage message);

// ---------------------------------------------------------------------------
// AppInitializer
// ---------------------------------------------------------------------------

/// Centralised Firebase boot sequence shared across all consumer apps.
///
/// Call [AppInitializer.init] at the very start of `main()`, before
/// [runApp], to perform all one-time platform and Firebase setup in one place.
///
/// ```dart
/// void main() async {
///   await AppInitializer.init(
///     options: DefaultFirebaseOptions.currentPlatform,
///     backgroundMessageHandler: _onBackgroundMessage,
///   );
///   runApp(const MyApp());
/// }
///
/// @pragma('vm:entry-point')
/// Future<void> _onBackgroundMessage(RemoteMessage message) async {
///   // Minimal work only — isolate may be killed at any time.
/// }
/// ```
///
/// What [init] does, in order:
///   1. Calls [WidgetsFlutterBinding.ensureInitialized].
///   2. Calls [Firebase.initializeApp] with [options].
///   3. Wires [FirebaseCrashlytics] into [FlutterError.onError] and
///      [PlatformDispatcher.instance.onError] (when [enableCrashlytics] is
///      `true`).
///   4. Registers [backgroundMessageHandler] via
///      [FirebaseMessaging.onBackgroundMessage] on non-web platforms.
///   5. Returns the initialised [FirebaseApp].
class AppInitializer {
  AppInitializer._();

  /// Initialises Flutter bindings, Firebase, Crashlytics, and FCM.
  ///
  /// - [options]: platform-specific Firebase configuration, typically
  ///   `DefaultFirebaseOptions.currentPlatform` generated by FlutterFire CLI.
  /// - [backgroundMessageHandler]: optional top-level FCM background handler.
  ///   Ignored on web. Must be annotated with `@pragma('vm:entry-point')`.
  /// - [enableCrashlytics]: when `true` (the default), Flutter and platform
  ///   errors are forwarded to Firebase Crashlytics.
  ///
  /// Returns the initialised [FirebaseApp] for apps that need it downstream.
  static Future<FirebaseApp> init({
    required FirebaseOptions options,
    FirebaseMessageHandler? backgroundMessageHandler,
    bool enableCrashlytics = true,
  }) async {
    WidgetsFlutterBinding.ensureInitialized();

    final app = await Firebase.initializeApp(options: options);

    // Crashlytics is not supported on web — skip silently.
    if (enableCrashlytics && !kIsWeb) {
      await _setupCrashlytics();
    }

    if (!kIsWeb && backgroundMessageHandler != null) {
      FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);
    }

    return app;
  }

  // ---------------------------------------------------------------------------
  // Crashlytics wiring
  // ---------------------------------------------------------------------------

  static Future<void> _setupCrashlytics() async {
    final crashlytics = FirebaseCrashlytics.instance;
    await crashlytics.setCrashlyticsCollectionEnabled(true);

    // Forward Flutter framework errors to Crashlytics.
    FlutterError.onError = crashlytics.recordFlutterFatalError;

    // Forward async/platform errors that escape the Flutter error handler.
    PlatformDispatcher.instance.onError = (error, stack) {
      crashlytics.recordError(error, stack, fatal: true);
      return true;
    };
  }
}
